### ISSUE TITLE
False emulator trigger on Xiaomi

### ISSUE THREAD

**Issue by Th0MmyS** [Safetorun/safe_to_run#99]
Some (or maybe all) Xiaomi devices have set Build.BOOTLOADER = "unknown"

because of that, every emulator check false triggers

these method are affected
banAvdEmulatorCheck()
banBluestacksEmulatorCheck()
banGenymotionEmulatorCheck()

**Comment by dllewellyn** [comment]
Thanks for submitting this! It should be relatively straightforward fix if we can create another check that only Xiaomi devices fix; do you happen to know what xiamoi devices return for `Build.MANUFACTURER`?

**Comment by dllewellyn** [comment]
Should now be fixed in 2.1.2
